package com.codevsolution.base.sqlite;

import android.net.Uri;

import com.codevsolution.base.javautil.JavaUtil;
import com.codevsolution.base.android.AppActivity;

import java.util.ArrayList;
import java.util.UUID;

import static com.codevsolution.base.logica.InteractorBase.Constantes.TABLAS;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.AMORTIZACION;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.CLIENTE;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.DETPARTIDA;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.DETPARTIDABASE;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.DETPEDIDOPROVCAT;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.DETPEDIDOPROVEEDOR;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.DIARIO;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.ESTADO;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.EVENTO;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.GASTOFIJO;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.NOTA;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.PARTIDA;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.PARTIDABASE;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.PEDIDOCLIENTE;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.PEDIDOPROVCAT;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.PEDIDOPROVEEDOR;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.PRODPROVCAT;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.PRODUCTO;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.PROVCAT;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.PROVEEDOR;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.PROYECTO;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.TIPOCLIENTE;
import static com.codevsolution.freemarketsapp.logica.Interactor.ConstantesPry.TRABAJO;

public class ContratoPry implements JavaUtil.Constantes {

    public static final String AUTORIDAD_CONTENIDO = AppActivity.getNombreApp();
    ;

    public static final Uri URI_BASE = Uri.parse("content://" + AUTORIDAD_CONTENIDO);

    public static final String BASE_CONTENIDOS = AUTORIDAD_CONTENIDO + ".";

    public static final String TIPO_CONTENIDO = "vnd.android.cursor.dir/vnd."
            + BASE_CONTENIDOS;

    public static final String TIPO_CONTENIDO_ITEM = "vnd.android.cursor.item/vnd."
            + BASE_CONTENIDOS;


    public interface Tablas {

        //TABLAS-----------------------------------------------------

        String TABLA_PROYECTO = PROYECTO;
        String TABLA_CLIENTE = CLIENTE;
        String TABLA_TIPOCLIENTE = TIPOCLIENTE;
        String TABLA_ESTADO = ESTADO;
        String TABLA_PARTIDA = PARTIDA;
        String TABLA_PERFIL = PERFIL;
        String TABLA_AMORTIZACION = AMORTIZACION;
        String TABLA_TRABAJO = TRABAJO;
        String TABLA_PRODUCTO = PRODUCTO;
        String TABLA_GASTOFIJO = GASTOFIJO;
        String TABLA_EVENTO = EVENTO;
        String TABLA_TABLAS = TABLAS;
        String TABLA_DETPARTIDA = DETPARTIDA;
        String TABLA_PARTIDABASE = PARTIDABASE;
        String TABLA_DETPARTIDABASE = DETPARTIDABASE;
        String TABLA_PROVEEDOR = PROVEEDOR;
        String TABLA_PEDIDOPROVCAT = PEDIDOPROVCAT;
        String TABLA_PEDIDOPROVEEDOR = PEDIDOPROVEEDOR;
        String TABLA_DETPEDIDOPROVCAT = DETPEDIDOPROVCAT;
        String TABLA_DETPEDIDOPROVEEDOR = DETPEDIDOPROVEEDOR;
        String TABLA_NOTA = NOTA;
        String TABLA_DIARIO = DIARIO;
        String TABLA_PEDIDOCLIENTE = PEDIDOCLIENTE;

        //COLUMNAS--------------------------------------------------------

        String PROYECTO_ID_PROYECTO = CAMPO_ID + TABLA_PROYECTO;
        String PROYECTO_ID_CLIENTE = CAMPO_ID + TABLA_CLIENTE + TABLA_PROYECTO;
        String PROYECTO_ID_ESTADO = CAMPO_ID + TABLA_ESTADO + TABLA_PROYECTO;
        String PROYECTO_NOMBRE = CAMPO_NOMBRE + TABLA_PROYECTO;
        String PROYECTO_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_PROYECTO;
        String PROYECTO_FECHAENTRADA = "fechaentrada_" + TABLA_PROYECTO;
        String PROYECTO_FECHAENTREGAPRESUP = "fechaentregapresup_" + TABLA_PROYECTO;
        String PROYECTO_FECHAENTREGAACORDADA = "fechaentregaacordada_" + TABLA_PROYECTO;
        String PROYECTO_FECHAENTREGACALCULADA = "fechaentregacalculada_" + TABLA_PROYECTO;
        String PROYECTO_FECHAFINAL = "fechafinal_" + TABLA_PROYECTO;
        String PROYECTO_FECHAENTRADAF = "fechaentradaf_" + TABLA_PROYECTO;
        String PROYECTO_FECHAENTREGAPRESUPF = "fechaentregapresupf_" + TABLA_PROYECTO;
        String PROYECTO_FECHAENTREGAACORDADAF = "fechaentregaacordadaf_" + TABLA_PROYECTO;
        String PROYECTO_FECHAENTREGACALCULADAF = "fechaentregacalculadaf_" + TABLA_PROYECTO;
        String PROYECTO_FECHAFINALF = "fechafinalf_" + TABLA_PROYECTO;
        String PROYECTO_RETRASO = "retraso_proyecto_" + TABLA_PROYECTO;
        String PROYECTO_IMPORTEPRESUPUESTO = "importepresupuesto_" + TABLA_PROYECTO;
        String PROYECTO_IMPORTEFINAL = "importefinal_" + TABLA_PROYECTO;
        String PROYECTO_COSTE = CAMPO_COSTE + TABLA_PROYECTO;
        String PROYECTO_TIEMPO = CAMPO_TIEMPO + TABLA_PROYECTO;
        String PROYECTO_RUTAFOTO = CAMPO_RUTAFOTO;
        String PROYECTO_RUTAPDF = "rutapdf_" + TABLA_PROYECTO;
        String PROYECTO_TOTCOMPLETADO = "totcomplet_" + TABLA_PROYECTO;
        String PROYECTO_CREATE = CAMPO_CREATEREG;
        String PROYECTO_TIMESTAMP = CAMPO_TIMESTAMP;
        //REFERENCIAS
        String PROYECTO_CLIENTE_NOMBRE = CAMPO_NOMBRE + TABLA_CLIENTE;
        String PROYECTO_CLIENTE_PESOTIPOCLI = "pesotipo_" + TABLA_CLIENTE;
        String PROYECTO_DESCRIPCION_ESTADO = CAMPO_DESCRIPCION + TABLA_ESTADO;
        String PROYECTO_TIPOESTADO = CAMPO_TIPO + TABLA_ESTADO;

        String CLIENTE_ID_CLIENTE = CAMPO_ID + TABLA_CLIENTE;
        String CLIENTE_ID_TIPOCLIENTE = CAMPO_ID + TABLA_TIPOCLIENTE + TABLA_CLIENTE;
        String CLIENTE_NOMBRE = CAMPO_NOMBRE + TABLA_CLIENTE;
        String CLIENTE_DIRECCION = CAMPO_DIRECCION + TABLA_CLIENTE;
        String CLIENTE_TELEFONO = CAMPO_TELEFONO + TABLA_CLIENTE;
        String CLIENTE_EMAIL = CAMPO_EMAIL + TABLA_CLIENTE;
        String CLIENTE_CONTACTO = CAMPO_CONTACTO + TABLA_CLIENTE;
        String CLIENTE_PESOTIPOCLI = "pesotipo_" + TABLA_CLIENTE;
        String CLIENTE_ACTIVO = CAMPO_ACTIVO + TABLA_CLIENTE;
        String CLIENTE_RUTAFOTO = CAMPO_RUTAFOTO;
        String CLIENTE_CREATE = CAMPO_CREATEREG;
        String CLIENTE_TIMESTAMP = CAMPO_TIMESTAMP;
        //REFERENCIAS
        String CLIENTE_TIPOCLIENTEPESO = "peso_" + TABLA_TIPOCLIENTE;
        String CLIENTE_DESCRIPCIONTIPOCLI = CAMPO_DESCRIPCION + TABLA_TIPOCLIENTE;

        String TIPOCLIENTE_ID_TIPOCLIENTE = CAMPO_ID + TABLA_TIPOCLIENTE;
        String TIPOCLIENTE_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_TIPOCLIENTE;
        String TIPOCLIENTE_PESO = "peso_" + TABLA_TIPOCLIENTE;

        String ESTADO_ID_ESTADO = CAMPO_ID + TABLA_ESTADO;
        String ESTADO_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_ESTADO;
        String ESTADO_TIPOESTADO = CAMPO_TIPO + TABLA_ESTADO;

        String PARTIDA_ID_PROYECTO = CAMPO_ID + TABLA_PARTIDA + TABLA_PROYECTO;
        String PARTIDA_ID_PARTIDA = CAMPO_ID + TABLA_PARTIDA;
        String PARTIDA_ID_PARTIDABASE = CAMPO_ID + TABLA_PARTIDA + TABLA_PARTIDABASE;
        String PARTIDA_SECUENCIA = CAMPO_SECUENCIA;
        String PARTIDA_ID_ESTADO = CAMPO_ID + TABLA_PARTIDA + TABLA_ESTADO;
        String PARTIDA_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_PARTIDA;
        String PARTIDA_NOMBRE = CAMPO_NOMBRE + TABLA_PARTIDA;
        String PARTIDA_CANTIDAD = CAMPO_CANTIDAD + TABLA_PARTIDA;
        String PARTIDA_TIEMPO = CAMPO_TIEMPO + TABLA_PARTIDA;
        String PARTIDA_TIEMPOREAL = "tiemporeal_" + TABLA_PARTIDA;
        String PARTIDA_CONTADOR = "contador_" + TABLA_PARTIDA;
        String PARTIDA_PRECIOHORA = "preciohora_" + TABLA_PARTIDA;
        String PARTIDA_PRECIO = CAMPO_PRECIO + TABLA_PARTIDA;
        String PARTIDA_COSTE = CAMPO_COSTE + TABLA_PARTIDA;
        String PARTIDA_COMPLETADA = "completada_" + TABLA_PARTIDA;
        String PARTIDA_COMPLETA = "completa_" + TABLA_PARTIDA;
        String PARTIDA_RUTAFOTO = CAMPO_RUTAFOTO;
        String PARTIDA_CREATE = CAMPO_CREATEREG;
        String PARTIDA_TIMESTAMP = CAMPO_TIMESTAMP;
        //REFERENCIAS
        String PARTIDA_PROYECTO_RETRASO = "retraso_proyecto_" + TABLA_PROYECTO;
        String PARTIDA_TIPO_ESTADO = CAMPO_TIPO + TABLA_ESTADO;


        String DETPARTIDA_ID_PARTIDA = CAMPO_ID + TABLA_DETPARTIDA + TABLA_PARTIDA;
        String DETPARTIDA_SECUENCIA = CAMPO_SECUENCIA;
        String DETPARTIDA_ID_DETPARTIDA = CAMPO_ID + TABLA_DETPARTIDA;
        String DETPARTIDA_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_DETPARTIDA;
        String DETPARTIDA_NOMBRE = CAMPO_NOMBRE + TABLA_DETPARTIDA;
        String DETPARTIDA_CANTIDAD = CAMPO_CANTIDAD + TABLA_DETPARTIDA;
        String DETPARTIDA_TIEMPO = CAMPO_TIEMPO + TABLA_DETPARTIDA;
        String DETPARTIDA_TIEMPOREAL = "tiemporeal_" + TABLA_DETPARTIDA;
        String DETPARTIDA_CONTADOR = "contador_" + TABLA_DETPARTIDA;
        String DETPARTIDA_PAUSA = "pausa_" + TABLA_DETPARTIDA;
        String DETPARTIDA_COMPLETADA = "completada_" + TABLA_DETPARTIDA;
        String DETPARTIDA_COMPLETA = "completa_" + TABLA_DETPARTIDA;
        String DETPARTIDA_PRECIO = CAMPO_PRECIO + TABLA_DETPARTIDA;
        String DETPARTIDA_COSTE = CAMPO_COSTE + TABLA_DETPARTIDA;
        String DETPARTIDA_BENEFICIO = CAMPO_BENEFICIO + TABLA_DETPARTIDA;
        String DETPARTIDA_DESCUENTOPROVCAT = "descuento_prov_cat_" + TABLA_DETPARTIDA;
        String DETPARTIDA_RUTAFOTO = CAMPO_RUTAFOTO;
        String DETPARTIDA_REFPROVCAT = "ref_prov_cat_" + TABLA_DETPARTIDA;
        String DETPARTIDA_DESCUENTOPROVEEDOR = "descuento_proveedor_" + TABLA_DETPARTIDA;
        String DETPARTIDA_REFPROVEEDOR = "ref_proveedor_" + TABLA_DETPARTIDA;
        String DETPARTIDA_TIPO = CAMPO_TIPO + TABLA_DETPARTIDA;
        String DETPARTIDA_CREATE = CAMPO_CREATEREG;
        String DETPARTIDA_TIMESTAMP = CAMPO_TIMESTAMP;

        String PARTIDABASE_ID_PARTIDABASE = CAMPO_ID + TABLA_PARTIDABASE;
        String PARTIDABASE_ID_PARTIDAORIGEN = CAMPO_ID + "partidaorigen_" + TABLA_PARTIDABASE;
        String PARTIDABASE_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_PARTIDABASE;
        String PARTIDABASE_NOMBRE = CAMPO_NOMBRE + TABLA_PARTIDABASE;
        String PARTIDABASE_TIEMPO = CAMPO_TIEMPO + TABLA_PARTIDABASE;
        String PARTIDABASE_PRECIO = CAMPO_PRECIO + TABLA_PARTIDABASE;
        String PARTIDABASE_COSTE = CAMPO_COSTE + TABLA_PARTIDABASE;
        String PARTIDABASE_RUTAFOTO = CAMPO_RUTAFOTO;
        String PARTIDABASE_CREATE = CAMPO_CREATEREG;
        String PARTIDABASE_TIMESTAMP = CAMPO_TIMESTAMP;

        String DETPARTIDABASE_ID_PARTIDABASE = CAMPO_ID + TABLA_DETPARTIDABASE + TABLA_PARTIDABASE;
        String DETPARTIDABASE_SECUENCIA = CAMPO_SECUENCIA;
        String DETPARTIDABASE_ID_DETPARTIDABASE = CAMPO_ID + TABLA_DETPARTIDABASE;
        String DETPARTIDABASE_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_DETPARTIDABASE;
        String DETPARTIDABASE_NOMBRE = CAMPO_NOMBRE + TABLA_DETPARTIDABASE;
        String DETPARTIDABASE_CANTIDAD = CAMPO_CANTIDAD + TABLA_DETPARTIDABASE;
        String DETPARTIDABASE_TIEMPO = CAMPO_TIEMPO + TABLA_DETPARTIDABASE;
        String DETPARTIDABASE_PRECIO = CAMPO_PRECIO + TABLA_DETPARTIDABASE;
        String DETPARTIDABASE_BENEFICIO = CAMPO_BENEFICIO + TABLA_DETPARTIDABASE;
        String DETPARTIDABASE_DESCUENTOPROVCAT = "descuentoprov_" + TABLA_DETPARTIDABASE;
        String DETPARTIDABASE_DESCUENTOPROVEEDOR = "descuentoproveedor_" + TABLA_DETPARTIDABASE;
        String DETPARTIDABASE_RUTAFOTO = CAMPO_RUTAFOTO;
        String DETPARTIDABASE_REFPROVCAT = "ref_prov_cat_" + TABLA_DETPARTIDABASE;
        String DETPARTIDABASE_REFPROVEEDOR = "ref_proveedor_" + TABLA_DETPARTIDABASE;
        String DETPARTIDABASE_TIPO = CAMPO_TIPO + TABLA_DETPARTIDABASE;
        String DETPARTIDABASE_CREATE = CAMPO_CREATEREG;
        String DETPARTIDABASE_TIMESTAMP = CAMPO_TIMESTAMP;

        String TRABAJO_ID_TRABAJO = CAMPO_ID + TABLA_TRABAJO;
        String TRABAJO_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_TRABAJO;
        String TRABAJO_NOMBRE = CAMPO_NOMBRE + TABLA_TRABAJO;
        String TRABAJO_TIEMPO = CAMPO_TIEMPO + TABLA_TRABAJO;
        String TRABAJO_RUTAFOTO = CAMPO_RUTAFOTO;
        String TRABAJO_CREATE = CAMPO_CREATEREG;
        String TRABAJO_TIMESTAMP = CAMPO_TIMESTAMP;

        String PRODUCTO_ID_PRODUCTO = CAMPO_ID + TABLA_PRODUCTO;
        String PRODUCTO_ID_PRODFIRE = CAMPO_ID + "fire_" + TABLA_PRODUCTO;
        String PRODUCTO_ID_PROVEEDOR = CAMPO_ID + TABLA_PROVEEDOR + TABLA_PRODUCTO;
        String PRODUCTO_ID_PROVFIRE = CAMPO_ID + "provfire_" + TABLA_PRODUCTO;
        String PRODUCTO_ID_CLON = CAMPO_ID + "clon_" + TABLA_PRODUCTO;
        String PRODUCTO_NOMBREPROV = "nombreprov_" + TABLA_PRODUCTO;
        String PRODUCTO_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_PRODUCTO;
        String PRODUCTO_NOMBRE = CAMPO_NOMBRE + TABLA_PRODUCTO;
        String PRODUCTO_WEB = "web_" + TABLA_PRODUCTO;
        String PRODUCTO_CATEGORIA = "categoria_" + TABLA_PRODUCTO;
        String PRODUCTO_ALCANCE = "alcance_" + TABLA_PRODUCTO;
        String PRODUCTO_TIPO = CAMPO_TIPO + TABLA_PRODUCTO;
        String PRODUCTO_ACTIVO = CAMPO_ACTIVO + TABLA_PRODUCTO;
        String PRODUCTO_SINCRO = "sincro_" + TABLA_PRODUCTO;
        String PRODUCTO_FIRE = "fire_" + TABLA_PRODUCTO;
        String PRODUCTO_PRECIO = CAMPO_PRECIO + TABLA_PRODUCTO;
        String PRODUCTO_REFERENCIA = CAMPO_REFERENCIA + TABLA_PRODUCTO;
        String PRODUCTO_DESCPROV = "descprov_" + TABLA_PRODUCTO;
        String PRODUCTO_RUTAFOTO = CAMPO_RUTAFOTO;
        String PRODUCTO_CREATE = CAMPO_CREATEREG;
        String PRODUCTO_TIMESTAMP = CAMPO_TIMESTAMP;

        String PROVEEDOR_ID_PROVEEDOR = CAMPO_ID + TABLA_PROVEEDOR;
        String PROVEEDOR_NOMBRE = CAMPO_NOMBRE + TABLA_CLIENTE;
        String PROVEEDOR_DIRECCION = CAMPO_DIRECCION + TABLA_PROVEEDOR;
        String PROVEEDOR_TELEFONO = CAMPO_TELEFONO + TABLA_PROVEEDOR;
        String PROVEEDOR_EMAIL = CAMPO_EMAIL + TABLA_PROVEEDOR;
        String PROVEEDOR_CONTACTO = CAMPO_CONTACTO + TABLA_PROVEEDOR;
        String PROVEEDOR_ACTIVO = CAMPO_ACTIVO + TABLA_PROVEEDOR;
        String PROVEEDOR_RUTAFOTO = CAMPO_RUTAFOTO;
        String PROVEEDOR_CREATE = CAMPO_CREATEREG;
        String PROVEEDOR_TIMESTAMP = CAMPO_TIMESTAMP;

        String GASTOFIJO_ID_GASTOFIJO = CAMPO_ID + TABLA_GASTOFIJO;
        String GASTOFIJO_NOMBRE = CAMPO_NOMBRE + TABLA_GASTOFIJO;
        String GASTOFIJO_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_GASTOFIJO;
        String GASTOFIJO_CANTIDAD = CAMPO_CANTIDAD + TABLA_GASTOFIJO;
        String GASTOFIJO_PRECIO = CAMPO_PRECIO + TABLA_GASTOFIJO;
        String GASTOFIJO_ANYOS = "anyos_" + TABLA_GASTOFIJO;
        String GASTOFIJO_MESES = "meses_" + TABLA_GASTOFIJO;
        String GASTOFIJO_DIAS = "dias_" + TABLA_GASTOFIJO;
        String GASTOFIJO_RUTAFOTO = CAMPO_RUTAFOTO;
        String GASTOFIJO_CREATE = CAMPO_CREATEREG;
        String GASTOFIJO_TIMESTAMP = CAMPO_TIMESTAMP;

        String PERFIL_ID_PERFIL = CAMPO_ID + TABLA_PERFIL;
        String PERFIL_NOMBRE = CAMPO_NOMBRE + TABLA_PERFIL;
        String PERFIL_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_PERFIL;
        String PERFIL_VACACIONES = "vacaciones_" + TABLA_PERFIL;
        String PERFIL_HORASLUNES = "hlunes_" + TABLA_PERFIL;
        String PERFIL_HORASMARTES = "hmartes_" + TABLA_PERFIL;
        String PERFIL_HORASMIERCOLES = "hmiercoles_" + TABLA_PERFIL;
        String PERFIL_HORASJUEVES = "hjueves_" + TABLA_PERFIL;
        String PERFIL_HORASVIERNES = "hviernes_" + TABLA_PERFIL;
        String PERFIL_HORASSABADO = "hsabado_" + TABLA_PERFIL;
        String PERFIL_HORASDOMINGO = "hdomingo_" + TABLA_PERFIL;
        String PERFIL_BENEFICIO = CAMPO_BENEFICIO + TABLA_PERFIL;
        String PERFIL_SUELDO = "sueldo_" + TABLA_PERFIL;
        String PERFIL_RUTAFOTO = CAMPO_RUTAFOTO;
        String PERFIL_CREATE = CAMPO_CREATEREG;
        String PERFIL_TIMESTAMP = CAMPO_TIMESTAMP;

        String AMORTIZACION_ID_AMORTIZACION = CAMPO_ID + TABLA_AMORTIZACION;
        String AMORTIZACION_NOMBRE = CAMPO_NOMBRE + TABLA_AMORTIZACION;
        String AMORTIZACION_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_AMORTIZACION;
        String AMORTIZACION_CANTIDAD = CAMPO_CANTIDAD + TABLA_AMORTIZACION;
        String AMORTIZACION_FECHACOMPRA = CAMPO_FECHA + TABLA_AMORTIZACION;
        String AMORTIZACION_FECHACOMPRAF = CAMPO_FECHAF + TABLA_AMORTIZACION;
        String AMORTIZACION_PRECIO = CAMPO_PRECIO + TABLA_AMORTIZACION;
        String AMORTIZACION_ANYOS = "anyos_" + TABLA_AMORTIZACION;
        String AMORTIZACION_MESES = "meses_" + TABLA_AMORTIZACION;
        String AMORTIZACION_DIAS = "dias_" + TABLA_AMORTIZACION;
        String AMORTIZACION_RUTAFOTO = CAMPO_RUTAFOTO;
        String AMORTIZACION_CREATE = CAMPO_CREATEREG;
        String AMORTIZACION_TIMESTAMP = CAMPO_TIMESTAMP;

        String EVENTO_ID_EVENTO = CAMPO_ID + TABLA_EVENTO;
        String EVENTO_IDMULTI = "id_multi" + TABLA_EVENTO;
        String EVENTO_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_EVENTO;
        String EVENTO_FECHAINIEVENTO = "fechaini_" + TABLA_EVENTO;
        String EVENTO_FECHAFINEVENTO = "fechafin_" + TABLA_EVENTO;
        String EVENTO_HORAINIEVENTO = "horaini_" + TABLA_EVENTO;
        String EVENTO_HORAFINEVENTO = "horafin_" + TABLA_EVENTO;
        String EVENTO_FECHAINIEVENTOF = "fechainif_" + TABLA_EVENTO;
        String EVENTO_FECHAFINEVENTOF = "fechafinf_" + TABLA_EVENTO;
        String EVENTO_HORAINIEVENTOF = "horainif_" + TABLA_EVENTO;
        String EVENTO_HORAFINEVENTOF = "horafinf_" + TABLA_EVENTO;
        String EVENTO_AVISO = "aviso_" + TABLA_EVENTO;
        String EVENTO_NOTIFICADO = "notificado_" + TABLA_EVENTO;
        String EVENTO_TELEFONO = CAMPO_TELEFONO + TABLA_EVENTO;
        String EVENTO_DIRECCION = CAMPO_DIRECCION + TABLA_EVENTO;
        String EVENTO_EMAIL = CAMPO_EMAIL + TABLA_EVENTO;
        String EVENTO_ASUNTO = "asunto_" + TABLA_EVENTO;
        String EVENTO_MENSAJE = "mensaje_" + TABLA_EVENTO;
        String EVENTO_RUTAADJUNTO = "rutaadjunto_" + TABLA_EVENTO;
        String EVENTO_PROYECTOREL = "proyectorel_" + TABLA_EVENTO;
        String EVENTO_NOMPROYECTOREL = "nomproyectorel_" + TABLA_EVENTO;
        String EVENTO_CLIENTEREL = "clienterel_" + TABLA_EVENTO;
        String EVENTO_NOMCLIENTEREL = "nomclienterel_" + TABLA_EVENTO;
        String EVENTO_TIPO = CAMPO_TIPO + TABLA_EVENTO;
        String EVENTO_RUTAFOTO = CAMPO_RUTAFOTO;
        String EVENTO_COMPLETADA = "completada_" + TABLA_EVENTO;
        String EVENTO_CREATE = CAMPO_CREATEREG;
        String EVENTO_TIMESTAMP = CAMPO_TIMESTAMP;

        String PEDIDOPROVCAT_ID_PEDIDOPROVCAT = CAMPO_ID + TABLA_PEDIDOPROVCAT;
        String PEDIDOPROVCAT_ID_PROYECTO = TABLA_PEDIDOPROVCAT + CAMPO_ID + TABLA_PROYECTO;
        String PEDIDOPROVCAT_ID_PROVCAT = TABLA_PEDIDOPROVCAT + CAMPO_ID + PROVCAT;
        String PEDIDOPROVCAT_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_PEDIDOPROVCAT;
        String PEDIDOPROVCAT_FECHA = CAMPO_FECHA + TABLA_PEDIDOPROVCAT;
        String PEDIDOPROVCAT_FECHAF = CAMPO_FECHAF + TABLA_PEDIDOPROVCAT;
        String PEDIDOPROVCAT_SERVIDO = CAMPO_SERVIDO + TABLA_PEDIDOPROVCAT;
        String PEDIDOPROVCAT_CREATE = CAMPO_CREATEREG;
        String PEDIDOPROVCAT_TIMESTAMP = CAMPO_TIMESTAMP;

        String DETPEDIDOPROVCAT_ID_PEDIDOPROVCAT = CAMPO_ID + TABLA_DETPEDIDOPROVCAT + TABLA_PEDIDOPROVCAT;
        String DETPEDIDOPROVCAT_SECUENCIA = CAMPO_SECUENCIA;
        String DETPEDIDOPROVCAT_ID_PRODPROVCAT = CAMPO_ID + PRODPROVCAT + TABLA_DETPEDIDOPROVCAT;
        String DETPEDIDOPROVCAT_REFERENCIA = CAMPO_REFERENCIA + TABLA_DETPEDIDOPROVCAT;
        String DETPEDIDOPROVCAT_NOMBRE = CAMPO_NOMBRE + TABLA_DETPEDIDOPROVCAT;
        String DETPEDIDOPROVCAT_CANTIDAD = CAMPO_CANTIDAD + TABLA_DETPEDIDOPROVCAT;
        String DETPEDIDOPROVCAT_PRECIO = CAMPO_PRECIO + TABLA_DETPEDIDOPROVCAT;
        String DETPEDIDOPROVCAT_SERVIDO = CAMPO_SERVIDO + TABLA_DETPEDIDOPROVCAT;
        String DETPEDIDOPROVCAT_CREATE = CAMPO_CREATEREG;
        String DETPEDIDOPROVCAT_TIMESTAMP = CAMPO_TIMESTAMP;

        String PEDIDOPROVEEDOR_ID_PEDIDOPROVEEDOR = CAMPO_ID + TABLA_PEDIDOPROVEEDOR;
        String PEDIDOPROVEEDOR_ID_PROYECTO = TABLA_PEDIDOPROVEEDOR + CAMPO_ID + TABLA_PROYECTO;
        String PEDIDOPROVEEDOR_ID_PROVEEDOR = TABLA_PEDIDOPROVEEDOR + CAMPO_ID + TABLA_PROVEEDOR;
        String PEDIDOPROVEEDOR_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_PEDIDOPROVEEDOR;
        String PEDIDOPROVEEDOR_FECHA = CAMPO_FECHA + TABLA_PEDIDOPROVEEDOR;
        String PEDIDOPROVEEDOR_FECHAF = CAMPO_FECHAF + TABLA_PEDIDOPROVEEDOR;
        String PEDIDOPROVEEDOR_SERVIDO = CAMPO_SERVIDO + TABLA_PEDIDOPROVEEDOR;
        String PEDIDOPROVEEDOR_CREATE = CAMPO_CREATEREG;
        String PEDIDOPROVEEDOR_TIMESTAMP = CAMPO_TIMESTAMP;

        String DETPEDIDOPROVEEDOR_ID_PEDIDOPROVEEDOR = CAMPO_ID + TABLA_DETPEDIDOPROVEEDOR + TABLA_PEDIDOPROVEEDOR;
        String DETPEDIDOPROVEEDOR_SECUENCIA = CAMPO_SECUENCIA;
        String DETPEDIDOPROVEEDOR_ID_PRODUCTO = CAMPO_ID + TABLA_PRODUCTO + TABLA_DETPEDIDOPROVEEDOR;
        String DETPEDIDOPROVEEDOR_REFERENCIA = CAMPO_REFERENCIA + TABLA_DETPEDIDOPROVEEDOR;
        String DETPEDIDOPROVEEDOR_NOMBRE = CAMPO_NOMBRE + TABLA_DETPEDIDOPROVEEDOR;
        String DETPEDIDOPROVEEDOR_CANTIDAD = CAMPO_CANTIDAD + TABLA_DETPEDIDOPROVEEDOR;
        String DETPEDIDOPROVEEDOR_PRECIO = CAMPO_PRECIO + TABLA_DETPEDIDOPROVEEDOR;
        String DETPEDIDOPROVEEDOR_SERVIDO = CAMPO_SERVIDO + TABLA_DETPEDIDOPROVEEDOR;
        String DETPEDIDOPROVEEDOR_CREATE = CAMPO_CREATEREG;
        String DETPEDIDOPROVEEDOR_TIMESTAMP = CAMPO_TIMESTAMP;

        String NOTA_ID_NOTA = CAMPO_ID + TABLA_NOTA;
        String NOTA_ID_RELACIONADO = "id_relacionado_" + TABLA_NOTA;
        String NOTA_NOMBREREL = "nombre_rel_" + TABLA_NOTA;
        String NOTA_TITULO = "titulo_" + TABLA_NOTA;
        String NOTA_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_NOTA;
        String NOTA_RUTAFOTO = CAMPO_RUTAFOTO;
        String NOTA_TIPO = CAMPO_TIPO + TABLA_NOTA;
        String NOTA_FECHA = CAMPO_FECHA + TABLA_NOTA;
        String NOTA_FECHAF = CAMPO_FECHAF + TABLA_NOTA;
        String NOTA_CREATE = CAMPO_CREATEREG;
        String NOTA_TIMESTAMP = CAMPO_TIMESTAMP;

        String DIARIO_ID_DIARIO = CAMPO_ID + TABLA_DIARIO;
        String DIARIO_ID_RELACIONADO = "id_relacionado_" + TABLA_DIARIO;
        String DIARIO_NOMBRE = CAMPO_NOMBRE + TABLA_DIARIO;
        String DIARIO_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_DIARIO;
        String DIARIO_NOMBREREL = "nombre_rel_" + TABLA_DIARIO;
        String DIARIO_REL = "rel_" + TABLA_DIARIO;
        String DIARIO_RUTAFOTO = CAMPO_RUTAFOTO;
        String DIARIO_CREATE = CAMPO_CREATEREG;
        String DIARIO_TIMESTAMP = CAMPO_TIMESTAMP;

        String PEDIDOCLIENTE_ID_PEDIDOCLIENTE = CAMPO_ID + TABLA_PEDIDOCLIENTE;
        String PEDIDOCLIENTE_ID_PROYECTO = TABLA_PEDIDOCLIENTE + CAMPO_ID + TABLA_PROYECTO;
        String PEDIDOCLIENTE_ID_CLIENTE = TABLA_PEDIDOCLIENTE + CAMPO_ID + TABLA_PROVEEDOR;
        String PEDIDOCLIENTE_DESCRIPCION = CAMPO_DESCRIPCION + TABLA_PEDIDOCLIENTE;
        String PEDIDOCLIENTE_FECHA = CAMPO_FECHA + TABLA_PEDIDOCLIENTE;
        String PEDIDOCLIENTE_FECHAF = CAMPO_FECHAF + TABLA_PEDIDOCLIENTE;
        String PEDIDOCLIENTE_NOMBRECLIENTE = "nombrecliente_" + TABLA_PEDIDOCLIENTE;
        String PEDIDOCLIENTE_CREATE = CAMPO_CREATEREG;
        String PEDIDOCLIENTE_TIMESTAMP = CAMPO_TIMESTAMP;

        String TABLAS_ID_TABLA = CAMPO_ID + TABLA_TABLAS;
        String TABLAS_TABLA = "tabla_" + TABLA_TABLAS;
        String TABLAS_CAMPO = "campo_" + TABLA_TABLAS;
        String TABLAS_PARAMETROS = "parametros_" + TABLA_TABLAS;
        String TABLAS_TIPODATO = "tipo_dato_" + TABLA_TABLAS;


        //REFERENCIAS----------------------------------------------------------

        String ID_PROYECTO = String.format("REFERENCES %s(%s) ON DELETE CASCADE",
                TABLA_PROYECTO, PROYECTO_ID_PROYECTO);
        String ID_PEDIDOPROVCAT = String.format("REFERENCES %s(%s) ON DELETE CASCADE",
                TABLA_PEDIDOPROVCAT, PEDIDOPROVCAT_ID_PEDIDOPROVCAT);
        String ID_PEDIDOPROVEEDOR = String.format("REFERENCES %s(%s) ON DELETE CASCADE",
                TABLA_PEDIDOPROVEEDOR, PEDIDOPROVEEDOR_ID_PEDIDOPROVEEDOR);

        String ID_CLIENTE = String.format("REFERENCES %s(%s)",
                TABLA_CLIENTE, CLIENTE_ID_CLIENTE);

        String ID_TIPOCLIENTE = String.format("REFERENCES %s(%s)",
                TABLA_TIPOCLIENTE, TIPOCLIENTE_ID_TIPOCLIENTE);

        String ID_ESTADO = String.format("REFERENCES %s(%s)",
                TABLA_ESTADO, ESTADO_ID_ESTADO);

        String ID_PRODUCTO = String.format("REFERENCES %s(%s)",
                TABLA_PRODUCTO, PRODUCTO_ID_PRODUCTO);

        String ID_TRABAJO = String.format("REFERENCES %s(%s)",
                TABLA_TRABAJO, TRABAJO_ID_TRABAJO);

        String ID_PARTIDA = String.format("REFERENCES %s(%s) ON DELETE CASCADE",
                TABLA_PARTIDA, PARTIDA_ID_PARTIDA);

        String ID_PARTIDABASE = String.format("REFERENCES %s(%s) ON DELETE CASCADE",
                TABLA_PARTIDABASE, PARTIDABASE_ID_PARTIDABASE);


        //CAMPOS----------------------------------------------------------------

        String[] CAMPOS_PROYECTO = {"77", TABLA_PROYECTO,
                PROYECTO_ID_PROYECTO, "TEXT NON NULL UNIQUE", STRING,
                PROYECTO_ID_CLIENTE, String.format("TEXT NON NULL %s", ID_CLIENTE), STRING,
                PROYECTO_ID_ESTADO, String.format("TEXT NON NULL %s", ID_ESTADO), STRING,
                PROYECTO_NOMBRE, "TEXT NON NULL", STRING,
                PROYECTO_DESCRIPCION, "TEXT NON NULL", STRING,
                PROYECTO_FECHAENTRADA, "INTEGER NON NULL DEFAULT 0", LONG,
                PROYECTO_FECHAENTREGAPRESUP, "INTEGER NON NULL DEFAULT 0", LONG,
                PROYECTO_FECHAENTREGAACORDADA, "INTEGER NON NULL DEFAULT 0", LONG,
                PROYECTO_FECHAENTREGACALCULADA, "INTEGER NON NULL DEFAULT 0", LONG,
                PROYECTO_FECHAFINAL, "INTEGER NON NULL DEFAULT 0", LONG,
                PROYECTO_FECHAENTRADAF, "TEXT", STRING,
                PROYECTO_FECHAENTREGAPRESUPF, "TEXT", STRING,
                PROYECTO_FECHAENTREGAACORDADAF, "TEXT", STRING,
                PROYECTO_FECHAENTREGACALCULADAF, "TEXT", STRING,
                PROYECTO_FECHAFINALF, "TEXT", STRING,
                PROYECTO_RETRASO, "INTEGER NON NULL DEFAULT 0", LONG,
                PROYECTO_IMPORTEPRESUPUESTO, "REAL NON NULL DEFAULT 0", DOUBLE,
                PROYECTO_IMPORTEFINAL, "REAL NON NULL DEFAULT 0", DOUBLE,
                PROYECTO_COSTE, "REAL NON NULL DEFAULT 0", DOUBLE,
                PROYECTO_TIEMPO, "REAL NON NULL DEFAULT 0", DOUBLE,
                PROYECTO_RUTAFOTO, "TEXT ", STRING,
                PROYECTO_RUTAPDF, "TEXT ", STRING,
                PROYECTO_TOTCOMPLETADO, "INTEGER NON NULL DEFAULT 0", INT,
                PROYECTO_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                PROYECTO_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG,
                //Campos referencia
                PROYECTO_CLIENTE_NOMBRE, NULL, STRING,
                PROYECTO_CLIENTE_PESOTIPOCLI, NULL, INT,
                PROYECTO_DESCRIPCION_ESTADO, NULL, STRING,
                PROYECTO_TIPOESTADO, NULL, INT
        };

        String[] CAMPOS_CLIENTE = {"38", TABLA_CLIENTE,
                CLIENTE_ID_CLIENTE, "TEXT NON NULL UNIQUE", STRING,
                CLIENTE_ID_TIPOCLIENTE, String.format("TEXT NON NULL %s", ID_TIPOCLIENTE), STRING,
                CLIENTE_NOMBRE, "TEXT NON NULL", STRING,
                CLIENTE_DIRECCION, "TEXT", STRING,
                CLIENTE_TELEFONO, "TEXT", STRING,
                CLIENTE_EMAIL, "TEXT", STRING,
                CLIENTE_CONTACTO, "TEXT", STRING,
                CLIENTE_RUTAFOTO, "TEXT", STRING,
                CLIENTE_PESOTIPOCLI, "INTEGER NON NULL DEFAULT 0", INT,
                CLIENTE_ACTIVO, "INTEGER NON NULL DEFAULT 0", LONG,
                CLIENTE_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                CLIENTE_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG,
                //Campos referencias
                CLIENTE_TIPOCLIENTEPESO, "", INT,
                CLIENTE_DESCRIPCIONTIPOCLI, "", STRING
        };

        String[] CAMPOS_TIPOCLIENTE = {"11", TABLA_TIPOCLIENTE,
                TIPOCLIENTE_ID_TIPOCLIENTE, "TEXT NON NULL UNIQUE", STRING,
                TIPOCLIENTE_DESCRIPCION, "TEXT NON NULL", STRING,
                TIPOCLIENTE_PESO, "INTEGER NON NULL", INT
        };

        String[] CAMPOS_ESTADO = {"11", TABLA_ESTADO,
                ESTADO_ID_ESTADO, "TEXT NON NULL UNIQUE", STRING,
                ESTADO_DESCRIPCION, "TEXT NON NULL", STRING,
                ESTADO_TIPOESTADO, "INTEGER NON NULL", INT
        };

        String[] CAMPOS_PARTIDA = {"56", TABLA_PARTIDA,
                PARTIDA_ID_PROYECTO, String.format("TEXT NON NULL %s", ID_PROYECTO), STRING,
                PARTIDA_ID_PARTIDA, "TEXT NON NULL UNIQUE", STRING,
                PARTIDA_ID_PARTIDABASE, "TEXT", STRING,
                PARTIDA_SECUENCIA, "INTEGER NON NULL", INT,
                PARTIDA_ID_ESTADO, String.format("TEXT NON NULL %s", ID_ESTADO), STRING,
                PARTIDA_DESCRIPCION, "TEXT NON NULL", STRING,
                PARTIDA_NOMBRE, "TEXT NON NULL", STRING,
                PARTIDA_CANTIDAD, "REAL NON NULL DEFAULT 0", DOUBLE,
                PARTIDA_TIEMPO, "REAL NON NULL DEFAULT 0", DOUBLE,
                PARTIDA_TIEMPOREAL, "REAL NON NULL DEFAULT 0", DOUBLE,
                PARTIDA_PRECIOHORA, "REAL NON NULL DEFAULT 0", DOUBLE,
                PARTIDA_PRECIO, "REAL NON NULL DEFAULT 0", DOUBLE,
                PARTIDA_COSTE, "REAL NON NULL DEFAULT 0", DOUBLE,
                PARTIDA_COMPLETADA, "REAL NON NULL DEFAULT 0", DOUBLE,
                PARTIDA_COMPLETA, "INTEGER NON NULL DEFAULT 0", INT,
                PARTIDA_RUTAFOTO, "TEXT", STRING,
                PARTIDA_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                PARTIDA_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG,
                //Campos referencias
                PARTIDA_PROYECTO_RETRASO, NULL, LONG,
                PARTIDA_TIPO_ESTADO, NULL, INT
        };

        String[] CAMPOS_DETPARTIDA = {"71", TABLA_DETPARTIDA,
                DETPARTIDA_ID_PARTIDA, String.format("TEXT NON NULL %s", ID_PARTIDA), STRING,
                DETPARTIDA_SECUENCIA, "INTEGER NON NULL", INT,
                DETPARTIDA_ID_DETPARTIDA, "TEXT", STRING,
                DETPARTIDA_NOMBRE, "TEXT NON NULL", STRING,
                DETPARTIDA_DESCRIPCION, "TEXT NON NULL", STRING,
                DETPARTIDA_CANTIDAD, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPARTIDA_TIEMPO, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPARTIDA_TIEMPOREAL, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPARTIDA_CONTADOR, "INTEGER NON NULL DEFAULT 0", LONG,
                DETPARTIDA_PAUSA, "INTEGER NON NULL DEFAULT 0", LONG,
                DETPARTIDA_COMPLETADA, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPARTIDA_COMPLETA, "INTEGER NON NULL DEFAULT 0", INT,
                DETPARTIDA_PRECIO, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPARTIDA_COSTE, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPARTIDA_BENEFICIO, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPARTIDA_DESCUENTOPROVCAT, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPARTIDA_DESCUENTOPROVEEDOR, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPARTIDA_RUTAFOTO, "TEXT", STRING,
                DETPARTIDA_REFPROVCAT, "TEXT", STRING,
                DETPARTIDA_REFPROVEEDOR, "TEXT", STRING,
                DETPARTIDA_TIPO, "TEXT NON NULL", STRING,
                DETPARTIDA_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                DETPARTIDA_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG

        };

        String[] CAMPOS_PARTIDABASE = {"32", TABLA_PARTIDABASE,
                PARTIDABASE_ID_PARTIDABASE, "TEXT NON NULL UNIQUE", STRING,
                PARTIDABASE_ID_PARTIDAORIGEN, "TEXT NON NULL UNIQUE", STRING,
                PARTIDABASE_DESCRIPCION, "TEXT NON NULL", STRING,
                PARTIDABASE_NOMBRE, "TEXT NON NULL", STRING,
                PARTIDABASE_TIEMPO, "REAL NON NULL DEFAULT 0", DOUBLE,
                PARTIDABASE_PRECIO, "REAL NON NULL DEFAULT 0", DOUBLE,
                PARTIDABASE_COSTE, "REAL NON NULL DEFAULT 0", DOUBLE,
                PARTIDABASE_RUTAFOTO, "TEXT", STRING,
                PARTIDABASE_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                PARTIDABASE_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG
        };

        String[] CAMPOS_DETPARTIDABASE = {"53", TABLA_DETPARTIDABASE,
                DETPARTIDABASE_ID_PARTIDABASE, String.format("TEXT NON NULL %s", ID_PARTIDABASE), STRING,
                DETPARTIDABASE_SECUENCIA, "INTEGER NON NULL", INT,
                DETPARTIDABASE_ID_DETPARTIDABASE, "TEXT", STRING,
                DETPARTIDABASE_NOMBRE, "TEXT NON NULL", STRING,
                DETPARTIDABASE_DESCRIPCION, "TEXT NON NULL", STRING,
                DETPARTIDABASE_CANTIDAD, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPARTIDABASE_TIEMPO, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPARTIDABASE_PRECIO, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPARTIDABASE_BENEFICIO, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPARTIDABASE_DESCUENTOPROVCAT, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPARTIDABASE_DESCUENTOPROVEEDOR, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPARTIDABASE_RUTAFOTO, "TEXT", STRING,
                DETPARTIDABASE_REFPROVCAT, "TEXT", STRING,
                DETPARTIDABASE_REFPROVEEDOR, "TEXT", STRING,
                DETPARTIDABASE_TIPO, "TEXT NON NULL", STRING,
                DETPARTIDABASE_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                DETPARTIDABASE_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG

        };

        String[] CAMPOS_TRABAJO = {"23", TABLA_TRABAJO,
                TRABAJO_ID_TRABAJO, "TEXT NON NULL UNIQUE", STRING,
                TRABAJO_DESCRIPCION, "TEXT NON NULL", STRING,
                TRABAJO_NOMBRE, "TEXT NON NULL", STRING,
                TRABAJO_RUTAFOTO, "TEXT", STRING,
                TRABAJO_TIEMPO, "REAL NON NULL DEFAULT 0", DOUBLE,
                TRABAJO_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                TRABAJO_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG
        };


        String[] CAMPOS_PRODUCTO = {"65", TABLA_PRODUCTO,
                PRODUCTO_ID_PRODUCTO, "TEXT NON NULL UNIQUE", STRING,
                PRODUCTO_ID_PRODFIRE, "TEXT", STRING,
                PRODUCTO_ID_CLON, "TEXT", STRING,
                PRODUCTO_ID_PROVFIRE, "TEXT", STRING,
                PRODUCTO_ID_PROVEEDOR, "TEXT", STRING,
                PRODUCTO_ALCANCE, "TEXT", STRING,
                PRODUCTO_CATEGORIA, "TEXT", STRING,
                PRODUCTO_TIPO, "TEXT", STRING,
                PRODUCTO_WEB, "TEXT", STRING,
                PRODUCTO_NOMBREPROV, "TEXT", STRING,
                PRODUCTO_DESCRIPCION, "TEXT", STRING,
                PRODUCTO_NOMBRE, "TEXT", STRING,
                PRODUCTO_REFERENCIA, "TEXT", STRING,
                PRODUCTO_RUTAFOTO, "TEXT", STRING,
                PRODUCTO_PRECIO, "REAL NON NULL DEFAULT 0", DOUBLE,
                PRODUCTO_DESCPROV, "REAL NON NULL DEFAULT 0", DOUBLE,
                PRODUCTO_ACTIVO, "INTEGER NON NULL DEFAULT 0", INT,
                PRODUCTO_SINCRO, "INTEGER NON NULL DEFAULT 0", INT,
                PRODUCTO_FIRE, "INTEGER NON NULL DEFAULT 0", INT,
                PRODUCTO_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                PRODUCTO_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG
        };

        String[] CAMPOS_GASTOFIJO = {"35", TABLA_GASTOFIJO,
                GASTOFIJO_ID_GASTOFIJO, "TEXT NON NULL UNIQUE", STRING,
                GASTOFIJO_NOMBRE, "TEXT NON NULL", STRING,
                GASTOFIJO_DESCRIPCION, "TEXT NON NULL", STRING,
                GASTOFIJO_CANTIDAD, "REAL NON NULL DEFAULT 0", DOUBLE,
                GASTOFIJO_PRECIO, "REAL NON NULL DEFAULT 0", DOUBLE,
                GASTOFIJO_ANYOS, "INTEGER NON NULL DEFAULT 0", INT,
                GASTOFIJO_MESES, "INTEGER NON NULL DEFAULT 0", INT,
                GASTOFIJO_DIAS, "INTEGER NON NULL DEFAULT 0", INT,
                GASTOFIJO_RUTAFOTO, "TEXT", STRING,
                GASTOFIJO_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                GASTOFIJO_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG
        };

        String[] CAMPOS_PERFIL = {"50", TABLA_PERFIL,
                PERFIL_ID_PERFIL, "TEXT NON NULL UNIQUE", STRING,
                PERFIL_NOMBRE, "TEXT NON NULL", STRING,
                PERFIL_DESCRIPCION, "TEXT NON NULL", STRING,
                PERFIL_VACACIONES, "INTEGER NON NULL DEFAULT 30", INT,
                PERFIL_HORASLUNES, "INTEGER NON NULL DEFAULT 8", INT,
                PERFIL_HORASMARTES, "INTEGER NON NULL DEFAULT 8", INT,
                PERFIL_HORASMIERCOLES, "INTEGER NON NULL DEFAULT 8", INT,
                PERFIL_HORASJUEVES, "INTEGER NON NULL DEFAULT 8", INT,
                PERFIL_HORASVIERNES, "INTEGER NON NULL DEFAULT 8", INT,
                PERFIL_HORASSABADO, "INTEGER NON NULL DEFAULT 0", INT,
                PERFIL_HORASDOMINGO, "INTEGER NON NULL DEFAULT 0", INT,
                PERFIL_BENEFICIO, "REAL NON NULL DEFAULT 10", DOUBLE,
                PERFIL_SUELDO, "REAL NON NULL DEFAULT 20000", DOUBLE,
                PERFIL_RUTAFOTO, "TEXT", STRING,
                PERFIL_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                PERFIL_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG
        };

        String[] CAMPOS_AMORTIZACION = {"41", TABLA_AMORTIZACION,
                AMORTIZACION_ID_AMORTIZACION, "TEXT NON NULL UNIQUE", STRING,
                AMORTIZACION_NOMBRE, "TEXT NON NULL", STRING,
                AMORTIZACION_DESCRIPCION, "TEXT NON NULL", STRING,
                AMORTIZACION_CANTIDAD, "REAL NON NULL", DOUBLE,
                AMORTIZACION_FECHACOMPRA, "INTEGER NON NULL DEFAULT 0", LONG,
                AMORTIZACION_FECHACOMPRAF, "TEXT", STRING,
                AMORTIZACION_PRECIO, "REAL NON NULL DEFAULT 0", DOUBLE,
                AMORTIZACION_ANYOS, "INTEGER NON NULL DEFAULT 0", INT,
                AMORTIZACION_MESES, "INTEGER NON NULL DEFAULT 0", INT,
                AMORTIZACION_DIAS, "INTEGER NON NULL DEFAULT 0", INT,
                AMORTIZACION_RUTAFOTO, "TEXT", STRING,
                AMORTIZACION_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                AMORTIZACION_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG
        };

        String[] CAMPOS_EVENTO = {"86", TABLA_EVENTO,
                EVENTO_ID_EVENTO, "TEXT NON NULL UNIQUE", STRING,
                EVENTO_IDMULTI, "TEXT NON NULL", STRING,
                EVENTO_DESCRIPCION, "TEXT NON NULL", STRING,
                EVENTO_FECHAINIEVENTO, "INTEGER NON NULL DEFAULT 0", LONG,
                EVENTO_FECHAFINEVENTO, "INTEGER NON NULL DEFAULT 0", LONG,
                EVENTO_HORAINIEVENTO, "INTEGER NON NULL DEFAULT 0", LONG,
                EVENTO_HORAFINEVENTO, "INTEGER NON NULL DEFAULT 0", LONG,
                EVENTO_FECHAINIEVENTOF, "TEXT", STRING,
                EVENTO_FECHAFINEVENTOF, "TEXT", STRING,
                EVENTO_HORAINIEVENTOF, "TEXT", STRING,
                EVENTO_HORAFINEVENTOF, "TEXT", STRING,
                EVENTO_AVISO, "INTEGER NON NULL DEFAULT 0", LONG,
                EVENTO_NOTIFICADO, "INTEGER NON NULL DEFAULT 0", INT,
                EVENTO_TELEFONO, "TEXT", STRING,
                EVENTO_DIRECCION, "TEXT", STRING,
                EVENTO_EMAIL, "TEXT", STRING,
                EVENTO_ASUNTO, "TEXT", STRING,
                EVENTO_MENSAJE, "TEXT", STRING,
                EVENTO_RUTAADJUNTO, "TEXT", STRING,
                EVENTO_PROYECTOREL, "TEXT", STRING,
                EVENTO_NOMPROYECTOREL, "TEXT", STRING,
                EVENTO_CLIENTEREL, "TEXT", STRING,
                EVENTO_NOMCLIENTEREL, "TEXT", STRING,
                EVENTO_TIPO, "TEXT NON NULL", STRING,
                EVENTO_RUTAFOTO, "TEXT", STRING,
                EVENTO_COMPLETADA, "REAL NON NULL DEFAULT 0", DOUBLE,
                EVENTO_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                EVENTO_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG
        };


        String[] CAMPOS_NOTA = {"35", TABLA_NOTA,
                NOTA_ID_NOTA, "TEXT NON NULL UNIQUE", STRING,
                NOTA_ID_RELACIONADO, "TEXT", STRING,
                NOTA_NOMBREREL, "TEXT", STRING,
                NOTA_TITULO, "TEXT", STRING,
                NOTA_DESCRIPCION, "TEXT", STRING,
                NOTA_RUTAFOTO, "TEXT", STRING,
                NOTA_FECHA, "INTEGER NON NULL DEFAULT 0", LONG,
                NOTA_FECHAF, "TEXT", STRING,
                NOTA_TIPO, "TEXT", STRING,
                NOTA_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                NOTA_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG

        };

        String[] CAMPOS_DIARIO = {"29", TABLA_DIARIO,
                DIARIO_ID_DIARIO, "TEXT NON NULL UNIQUE", STRING,
                DIARIO_ID_RELACIONADO, "TEXT NON NULL", STRING,
                DIARIO_NOMBRE, "TEXT NON NULL", STRING,
                DIARIO_NOMBREREL, "TEXT NON NULL", STRING,
                DIARIO_DESCRIPCION, "TEXT NON NULL", STRING,
                DIARIO_RUTAFOTO, "TEXT NON NULL", STRING,
                DIARIO_REL, "TEXT NON NULL", STRING,
                DIARIO_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                DIARIO_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG


        };

        String[] CAMPOS_PROVEEDOR = {"32", TABLA_PROVEEDOR,
                PROVEEDOR_ID_PROVEEDOR, "TEXT NON NULL UNIQUE", STRING,
                PROVEEDOR_NOMBRE, "TEXT NON NULL", STRING,
                PROVEEDOR_DIRECCION, "TEXT", STRING,
                PROVEEDOR_TELEFONO, "TEXT", STRING,
                PROVEEDOR_EMAIL, "TEXT", STRING,
                PROVEEDOR_CONTACTO, "TEXT", STRING,
                PROVEEDOR_RUTAFOTO, "TEXT", STRING,
                PROVEEDOR_ACTIVO, "INTEGER NON NULL DEFAULT 0", LONG,
                PROVEEDOR_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                PROVEEDOR_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG
        };

        String[] CAMPOS_PEDIDOPROVCAT = {"29", TABLA_PEDIDOPROVCAT,
                PEDIDOPROVCAT_ID_PEDIDOPROVCAT, "TEXT NON NULL UNIQUE", STRING,
                PEDIDOPROVCAT_ID_PROYECTO, String.format("TEXT NON NULL %s", ID_PROYECTO), STRING,
                PEDIDOPROVCAT_ID_PROVCAT, "TEXT NON NULL", STRING,
                PEDIDOPROVCAT_DESCRIPCION, "TEXT NON NULL", STRING,
                PEDIDOPROVCAT_FECHA, "INTEGER NON NULL DEFAULT 0", LONG,
                PEDIDOPROVCAT_FECHAF, "TEXT", STRING,
                PEDIDOPROVCAT_SERVIDO, "INTEGER NON NULL DEFAULT 0", LONG,
                PEDIDOPROVCAT_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                PEDIDOPROVCAT_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG
        };

        String[] CAMPOS_DETPEDIDOPROVCAT = {"32", TABLA_DETPEDIDOPROVCAT,
                DETPEDIDOPROVCAT_ID_PEDIDOPROVCAT, String.format("TEXT NON NULL %s", ID_PEDIDOPROVCAT), STRING,
                DETPEDIDOPROVCAT_SECUENCIA, "INTEGER NON NULL", INT,
                DETPEDIDOPROVCAT_ID_PRODPROVCAT, "TEXT NON NULL", STRING,
                DETPEDIDOPROVCAT_REFERENCIA, "TEXT", STRING,
                DETPEDIDOPROVCAT_NOMBRE, "TEXT NON NULL", STRING,
                DETPEDIDOPROVCAT_CANTIDAD, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPEDIDOPROVCAT_PRECIO, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPEDIDOPROVCAT_SERVIDO, "INTEGER NON NULL DEFAULT 0", STRING,
                DETPEDIDOPROVCAT_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                DETPEDIDOPROVCAT_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG
        };

        String[] CAMPOS_PEDIDOPROVEEDOR = {"29", TABLA_PEDIDOPROVEEDOR,
                PEDIDOPROVEEDOR_ID_PEDIDOPROVEEDOR, "TEXT NON NULL UNIQUE", STRING,
                PEDIDOPROVEEDOR_ID_PROYECTO, String.format("TEXT NON NULL %s", ID_PROYECTO), STRING,
                PEDIDOPROVEEDOR_ID_PROVEEDOR, "TEXT NON NULL", STRING,
                PEDIDOPROVEEDOR_DESCRIPCION, "TEXT NON NULL", STRING,
                PEDIDOPROVEEDOR_FECHA, "INTEGER NON NULL DEFAULT 0", LONG,
                PEDIDOPROVEEDOR_FECHAF, "TEXT", STRING,
                PEDIDOPROVEEDOR_SERVIDO, "INTEGER NON NULL DEFAULT 0", LONG,
                PEDIDOPROVEEDOR_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                PEDIDOPROVEEDOR_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG
        };

        String[] CAMPOS_DETPEDIDOPROVEEDOR = {"32", TABLA_DETPEDIDOPROVEEDOR,
                DETPEDIDOPROVEEDOR_ID_PEDIDOPROVEEDOR, String.format("TEXT NON NULL %s", ID_PEDIDOPROVEEDOR), STRING,
                DETPEDIDOPROVEEDOR_SECUENCIA, "INTEGER NON NULL", INT,
                DETPEDIDOPROVEEDOR_ID_PRODUCTO, "TEXT NON NULL", STRING,
                DETPEDIDOPROVEEDOR_REFERENCIA, "TEXT", STRING,
                DETPEDIDOPROVEEDOR_NOMBRE, "TEXT NON NULL", STRING,
                DETPEDIDOPROVEEDOR_CANTIDAD, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPEDIDOPROVEEDOR_PRECIO, "REAL NON NULL DEFAULT 0", DOUBLE,
                DETPEDIDOPROVEEDOR_SERVIDO, "INTEGER NON NULL DEFAULT 0", STRING,
                DETPEDIDOPROVEEDOR_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                DETPEDIDOPROVEEDOR_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG
        };

        String[] CAMPOS_PEDIDOCLIENTE = {"29", TABLA_PEDIDOCLIENTE,
                PEDIDOCLIENTE_ID_PEDIDOCLIENTE, "TEXT NON NULL UNIQUE", STRING,
                PEDIDOCLIENTE_ID_PROYECTO, String.format("TEXT NON NULL %s", ID_PROYECTO), STRING,
                PEDIDOCLIENTE_ID_CLIENTE, "TEXT NON NULL", STRING,
                PEDIDOCLIENTE_DESCRIPCION, "TEXT NON NULL", STRING,
                PEDIDOCLIENTE_FECHA, "INTEGER NON NULL DEFAULT 0", LONG,
                PEDIDOCLIENTE_FECHAF, "TEXT", STRING,
                PEDIDOCLIENTE_NOMBRECLIENTE, "TEXT", STRING,
                PEDIDOCLIENTE_CREATE, "INTEGER NON NULL DEFAULT 0", LONG,
                PEDIDOCLIENTE_TIMESTAMP, "INTEGER NON NULL DEFAULT 0", LONG
        };


    }

    public static final String PARAMETRO_FILTRO = "filtro";
    public static final String FILTRO_CLIENTE = "cliente";
    public static final String FILTRO_TOTAL = "total";
    public static final String FILTRO_FECHA = "fecha";
    public static final String FILTRO_ESTADO = "estado";
    public static final String FILTRO_RETRASO = "retraso";

    public static ArrayList<String[]> obtenerListaCampos() {

        ArrayList<String[]> listaCampos = new ArrayList<>();
        listaCampos.add(Tablas.CAMPOS_PROYECTO);
        listaCampos.add(Tablas.CAMPOS_CLIENTE);
        listaCampos.add(Tablas.CAMPOS_TIPOCLIENTE);
        listaCampos.add(Tablas.CAMPOS_ESTADO);
        listaCampos.add(Tablas.CAMPOS_EVENTO);
        listaCampos.add(Tablas.CAMPOS_PARTIDA);
        listaCampos.add(Tablas.CAMPOS_TRABAJO);
        listaCampos.add(Tablas.CAMPOS_PRODUCTO);
        listaCampos.add(Tablas.CAMPOS_GASTOFIJO);
        listaCampos.add(Tablas.CAMPOS_AMORTIZACION);
        listaCampos.add(Tablas.CAMPOS_PERFIL);
        listaCampos.add(Tablas.CAMPOS_DETPARTIDA);
        listaCampos.add(Tablas.CAMPOS_PARTIDABASE);
        listaCampos.add(Tablas.CAMPOS_DETPARTIDABASE);
        listaCampos.add(Tablas.CAMPOS_PEDIDOPROVCAT);
        listaCampos.add(Tablas.CAMPOS_NOTA);
        listaCampos.add(Tablas.CAMPOS_DIARIO);
        listaCampos.add(Tablas.CAMPOS_PROVEEDOR);
        listaCampos.add(Tablas.CAMPOS_PEDIDOPROVEEDOR);
        listaCampos.add(Tablas.CAMPOS_DETPEDIDOPROVEEDOR);
        listaCampos.add(Tablas.CAMPOS_DETPEDIDOPROVCAT);
        listaCampos.add(Tablas.CAMPOS_PEDIDOCLIENTE);

        return listaCampos;
    }

    public static String[] obtenerCampos(String tabla) {

        ArrayList<String[]> listaCampos = obtenerListaCampos();

        for (String[] campo : listaCampos) {
            if (campo[1].equals(tabla)) {
                return campo;
            }
        }

        return null;
    }

    public static String getTabCab(String tabla) {

        switch (tabla) {

            case Tablas.TABLA_PARTIDA:

                return Tablas.TABLA_PROYECTO;

            case Tablas.TABLA_DETPARTIDA:

                return Tablas.TABLA_PARTIDA;

            case Tablas.TABLA_DETPARTIDABASE:

                return Tablas.TABLA_PARTIDABASE;

            case Tablas.TABLA_PEDIDOPROVCAT:

                return Tablas.TABLA_PROYECTO;

            case Tablas.TABLA_DETPEDIDOPROVCAT:

                return Tablas.TABLA_PEDIDOPROVCAT;

            case Tablas.TABLA_PEDIDOPROVEEDOR:

                return Tablas.TABLA_PROYECTO;

            case Tablas.TABLA_DETPEDIDOPROVEEDOR:

                return Tablas.TABLA_PEDIDOPROVEEDOR;

        }

        return null;
    }

    public static Uri obtenerUriContenido(String tabla) {

        return URI_BASE.buildUpon().appendPath(tabla).build();
    }

    public static Uri crearUriTabla(String id, String tabla) {

        Uri URI_CONTENIDO = obtenerUriContenido(tabla);

        return URI_CONTENIDO.buildUpon().appendPath(id).build();
    }

    public static Uri crearUriTablaDetalle(String id, String secuencia, String tabla) {
        // Uri de la forma 'gasto/:id#:secuencia'
        Uri URI_CONTENIDO = obtenerUriContenido(tabla);
        return URI_CONTENIDO.buildUpon()
                .appendPath(String.format("%s#%s", id, secuencia))
                .build();
    }

    public static Uri crearUriTablaDetalle(String id, int secuencia, String tabla) {
        // Uri de la forma 'gasto/:id#:secuencia'
        Uri URI_CONTENIDO = obtenerUriContenido(tabla);
        return URI_CONTENIDO.buildUpon()
                .appendPath(String.format("%s#%s", id, String.valueOf(secuencia)))
                .build();
    }

    public static Uri crearUriTablaDetalleId(String id, String tabla, String tablaCab) {

        Uri URI_CONTENIDO = obtenerUriContenido(tablaCab);
        return URI_CONTENIDO.buildUpon().appendPath(id).appendPath(tabla).build();

    }

    public static String obtenerIdTablaDetalleId(Uri uri) {
        return uri.getPathSegments().get(1);
    }

    public static String[] obtenerIdTablaDetalle(Uri uri) {
        return uri.getLastPathSegment().split("#");
    }

    public static String generarIdTabla(String tabla) {
        return tabla + UUID.randomUUID().toString();
    }

    public static String obtenerIdTabla(Uri uri) {
        return uri.getLastPathSegment();
    }

    public static boolean tieneFiltro(Uri uri) {
        return uri != null && uri.getQueryParameter(PARAMETRO_FILTRO) != null;
    }


    public static String generarMime(String id) {
        if (id != null) {
            return TIPO_CONTENIDO + id;
        } else {
            return null;
        }
    }

    public static String generarMimeItem(String id) {
        if (id != null) {
            return TIPO_CONTENIDO_ITEM + id;
        } else {
            return null;
        }
    }


    private ContratoPry() {
    }
}
